/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.4.6.v200905071426
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package org.tmforum.tip.common.events;


/**
 * This is a generic event definition used to provide an update about the status of a process.
 *
 * @tigerstripe.event
 *      isSingleExtensionType="false"
 *		isAbstract = "false"
 *		implements = ""
 *
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("
 *      generate = "true"
 *
 * @tigerstripe.stereotype st.name = "version"
 *    revision = ""
 *    minor = "01"
 *    major = "00"
 * 
 */
public class ProcessStatus
  extends org.tmforum.tip.common.events.BaseEvent
 {




    /**
     * The progress level in percentage of the process execution.
     * @tigerstripe.field 
     *  isOptional = "false"
     *  isReadOnly = "false"
     *  isOrdered = "false"
     *  isUnique = "true"
     *  typeMultiplicity = "1"
     *   ref-by = "value"
     *
     *
     * 
     */
	public int percentComplete;


    /**
     * The state of the process.
     * @tigerstripe.field 
     *  isOptional = "false"
     *  isReadOnly = "false"
     *  isOrdered = "false"
     *  isUnique = "true"
     *  typeMultiplicity = "1"
     *  defaultValue = "IN_PROGRESS" 
     *   ref-by = "value"
     *
     *
     * 
     */
	public org.tmforum.tip.common.events.ProcessStates state;

}