/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.4.6.v200905071426
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package org.tmforum.tip.common.events;


/**
 * The definition of a simple process execution states.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("
 *      generate = "true"
 *
 * @tigerstripe.stereotype st.name = "version"
 *    revision = ""
 *    minor = "01"
 *    major = "00"
 * 
 */
public abstract class ProcessStates
 {


    /**
     * The process is active.
     * @tigerstripe.label
     *  value = '"0"'
     *  
     *
     * 
     */
    public final static java.lang.String IN_PROGRESS = "0";


    /**
     * The process is finished.
     * @tigerstripe.label
     *  value = '"1"'
     *  
     *
     * 
     */
    public final static java.lang.String COMPLETED = "1";


    /**
     * The process has failed.
     * @tigerstripe.label
     *  value = '"2"'
     *  
     *
     * 
     */
    public final static java.lang.String FAILED = "2";

}