/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.4.6.v200905071426
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package org.tmforum.tip.common.exceptions;


/**
 * This is the base definition of all TIP operation exceptions.
 *
 * @tigerstripe.exception
 *		isAbstract = "true"
 *		implements = ""
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("
 *      generate = "true"
 *
 * @tigerstripe.stereotype st.name = "version"
 *    revision = ""
 *    minor = "01"
 *    major = "00"
 * 
 */
public abstract class BaseException
  extends java.lang.Exception
 {
	
	// not important since this class will never be serialized.
	private static final long serialVersionUID = -1L;



    /**
     * Free string to define the reason the exception was raised.
     * @tigerstripe.field 
     *  isOptional = "false"
     *  isReadOnly = "false"
     *  isOrdered = "false"
     *  isUnique = "true"
     *  typeMultiplicity = "1"
     *   ref-by = "value"
     *
     *
     * 
     */
	public java.lang.String reason;


    /**
     * The more specific details about the exception.
     * @tigerstripe.field 
     *  isOptional = "false"
     *  isReadOnly = "false"
     *  isOrdered = "false"
     *  isUnique = "true"
     *  typeMultiplicity = "1"
     *   ref-by = "value"
     *
     *
     * 
     */
	public java.lang.String details;


}