/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.4.6.v200905071426
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package org.tmforum.tip.common.exceptions;


/**
 * This is the type of exception raised for all underlying communication failures.
 *
 * @tigerstripe.exception
 *		isAbstract = "false"
 *		implements = ""
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("
 *      generate = "true"
 * * 
 */
public abstract class CommunicationLoss
  extends org.tmforum.tip.common.exceptions.BaseException
 {
	
	// not important since this class will never be serialized.
	private static final long serialVersionUID = -1L;



}